services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${WAYFER_DATABASE_USER}
      POSTGRES_DB: ${WAYFER_DATABASE_NAME}
      POSTGRES_PASSWORD: ${WAYFER_DATABASE_PASSWORD}
    volumes:
        - db:/var/lib/postgresql/data



volumes:
  db:
    driver: local
